[package]
name = "suprnova-lsp-zed"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Zed language server adapter for Suprnova LSP."
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api.workspace = true

[lints]
workspace = true
