[book]
title = "Suprnova LSP"
authors = ["Igor Aleksanov"]
description = "Documentation for the suprnova-lsp Rust language server."
language = "en"
src = "src"

[rust]
edition = "2024"

[build]
build-dir = "../target/book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/eas4ai/suprnova-lsp"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/eas4ai/suprnova-lsp/edit/main/docs/{path}"
